# fly.toml app configuration file generated for digital-book-shop on 2024-10-27T10:21:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'digital-book-shop'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
memory_mb = 256
cpu_kind = 'shared'
cpus = 1

[[restart]]
policy = "on-failure"
retries = 1
processes = ["app"]
